output "ssh_key" {
  description = "ssh key generated by terraform"
  value = tls_private_key.generated-ssh-key.private_key_pem
  sensitive = true
}

output "elastic_ip" {
  value = module.Network.elastic_ip
}

output "public_ip" {
  value = module.EC2.instance_ip
}
